# Generated by Django 5.2.3 on 2025-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brique1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='listes_taches',
            field=models.ManyToManyField(related_name='taches', to='brique1.listetache'),
        ),
    ]
