# Generated by Django 5.2.3 on 2025-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brique1', '0004_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
